# This file is part of the DUDS project. It is subject to the BSD-style
# license terms in the LICENSE file found in the top-level directory of this
# distribution and at https://github.com/jjackowski/duds/blob/master/LICENSE.
# No part of DUDS, including this file, may be copied, modified, propagated,
# or distributed except according to the terms contained in the LICENSE file.
#
# Copyright (C) 2017  Jeff Jackowski

Import('*')

LinuxIfSource = Glob('hardware/interface/linux/[A-FH-Z]*cpp')
if env['Use_GpioDevPort']:
	LinuxIfSource += Glob('hardware/interface/linux/G*cpp')

LinuxOsSource = Glob('os/linux/[A-DF-HJ-Z]*cpp')
if env['Use_Evdev']:
	env.Append(
		CPPPATH = '$EVDEVINC',
		LIBS = 'evdev'
	)
	LinuxOsSource += Glob('os/linux/[EI]*cpp')

targets = [
	# include all source files in the DUDS library using a very simple method
	env.SharedLibrary('duds', Glob('*.cpp') + Glob('*/*.cpp') +
		Glob('[a-np-z]*/*/*.cpp') + LinuxIfSource + Glob('*/devices/*/*cpp') +
		Glob('ui/menu/renderers/*.cpp') + Glob('*/*/test/*.cpp') +
		LinuxOsSource),
	# changed to static temporarily to ease the use of eclipse programs and
	# delay learning more about software installs
	#env.StaticLibrary('duds', Glob('*.cpp') + Glob('*/*.cpp') +
	#	Glob('*/*/*.cpp') + Glob('*/*/linux/*cpp') + Glob('*/devices/*/*cpp') )
		# + Glob('*/*/*/*.cpp') +  Glob('*/*/*/*/*.cpp'))
		# above changed to just have linux only to help build new code & fix
		# up old code; do change it back
]

Return('targets')
